# 範例一

In [1]:
import numpy as np
import matplotlib.pyplot as plt  # To visualize
import pandas as pd  # To read data

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/LiShingHan/DataScience/main/DataSet/p6.4.csv')  # load data set
data

outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  warm     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  warm     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  warm   normal  False  yes
10     sunny  warm   normal   True  yes
11  overcast  warm     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  warm     high   True   no

In [3]:
target = data['play']
target.columns = ['play']

In [4]:
features_dataframe = data.loc[:, data.columns != 'play']
features_dataframe = pd.get_dummies(features_dataframe) 
features_dataframe.columns

Index(['windy', 'outlook_overcast', 'outlook_rainy', 'outlook_sunny',
       'temp_cool', 'temp_hot', 'temp_warm', 'humidity_high',
       'humidity_normal'],
      dtype='object')

In [5]:
features_dataframe

windy  outlook_overcast  outlook_rainy  outlook_sunny  temp_cool  \
0   False                 0              0              1          0   
1    True                 0              0              1          0   
2   False                 1              0              0          0   
3   False                 0              1              0          0   
4   False                 0              1              0          1   
5    True                 0              1              0          1   
6    True                 1              0              0          1   
7   False                 0              0              1          0   
8   False                 0              0              1          1   
9   False                 0              1              0          0   
10   True                 0              0              1          0   
11   True                 1              0              0          0   
12  False                 1              0              0          0   
13   True                 0              1              0          0   

    temp_hot  temp_warm  humidity_high  humidity_normal  
0          1          0              1                0  
1          1          0              1                0  
2          1          0              1                0  
3          0          1              1                0  
4          0          0              0                1  
5          0          0              0                1  
6          0          0              0                1  
7          0          1              1                0  
8          0          0              0                1  
9          0          1              0                1  
10         0          1              0                1  
11         0          1              1                0  
12         1          0              0                1  
13         0          1              1                0

In [6]:
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
le = preprocessing.LabelEncoder()
le.fit(target.values)

k = le.transform(target.values)
k

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [8]:
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)

In [9]:
classifier.fit(features_dataframe, k)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [10]:
y_pred = classifier.predict(features_dataframe)
y_pred

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [11]:
# Making a confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(k, y_pred)
cm

array([[5, 0],
       [0, 9]])

In [12]:
# Accuracy result
from sklearn.metrics import accuracy_score
ac= accuracy_score(k, y_pred)
ac

1.0

# 範例二

In [13]:
import numpy as np                 
import pandas as pd                
import matplotlib.pyplot as plt        

In [15]:
dataset = pd.read_csv('https://raw.githubusercontent.com/LiShingHan/DataScience/main/DataSet/Random%20forest.csv')
X = dataset.iloc[:,[2, 3]].values    # predictor attribute
y = dataset.iloc[:,-1].values        # target attribute


In [16]:

# split the dataset into test set and train set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y, test_size=0.2, random_state=0)

In [17]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test  = sc.fit_transform(X_test)

In [18]:

# import random forest classifier model from scikit learn
from sklearn.ensemble import RandomForestClassifier

In [19]:

# initialize the model
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)

In [20]:
# fit the train data into our model
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [21]:
# Making a prediction
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [22]:
# Making a confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
cm

array([[53,  5],
       [ 1, 21]])

In [23]:
# Accuracy result
from sklearn.metrics import accuracy_score
ac= accuracy_score(y_test, y_pred)
ac

0.925