# K-Nearest Neighbors

# https://www.mdeditor.tw/pl/2x0j/zh-tw
# https://www.analyticsvidhya.com/blog/2018/08/k-nearest-neighbor-introduction-regression-python/

In [1]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=7093dcdbc240490583c08ae0ec2683e3131a7155ecd30776d31c9f6b3f86ba8c
  Stored in directory: /root/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [2]:
import numpy as np
import matplotlib.pyplot as plt  # To visualize
import pandas as pd  # To read data

In [4]:
data = pd.read_csv('https://raw.githubusercontent.com/LiShingHan/DataScience/main/DataSet/KNN.csv')  # load data set
data

Height  Age  Weight
0    5.00   45      77
1    5.11   26      47
2    5.60   30      55
3    5.90   34      59
4    4.80   40      72
5    5.80   36      60
6    5.30   19      40
7    5.80   28      60
8    5.50   23      45
9    5.60   32      58

In [5]:
X=data.iloc[:,:-1].values    # predictor attributes
y=data.iloc[:,-1].values     # target attributes

In [6]:
y

array([77, 47, 55, 59, 72, 60, 40, 60, 45, 58])

In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
X_data=sc_X.fit_transform(X)
X_data

array([[-1.24371496,  1.84046046],
       [-0.93349127, -0.71200295],
       [ 0.44841424, -0.17464223],
       [ 1.29447884,  0.36271849],
       [-1.80775803,  1.16875956],
       [ 1.0124573 ,  0.63139884],
       [-0.39765036, -1.65238421],
       [ 1.0124573 , -0.44332259],
       [ 0.1663927 , -1.11502349],
       [ 0.44841424,  0.09403813]])

In [8]:
from sklearn import neighbors

In [9]:
model = neighbors.KNeighborsRegressor(n_neighbors = 3)
model.fit(X_data, y)  #fit the model
X_test = [[5.5, 38]]
pred=model.predict(X_test) #make prediction on test set
pred

## ID11 = (77+72+60)/3 
## ID11 = 69.66 kg


array([69.66666667])

In [10]:
model = neighbors.KNeighborsRegressor(n_neighbors = 5)
model.fit(X_data, y)  #fit the model
X_test = [[5.5, 38]]
pred=model.predict(X_test) #make prediction on test set
pred

# ID 11 =  (77+59+72+60+58)/5 
# ID 11 = 65.2 kg

array([65.2])