# Neural Networks

# https://www.python-course.eu/neural_networks_with_scikit.php

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

In [2]:
iris = load_iris()


iris.label contains the labels 0, 1 and 2 corresponding three species of Iris flower:

--Iris setosa,
--Iris virginica and
--Iris versicolor.


In [3]:

# splitting into train and test datasets

from sklearn.model_selection import train_test_split

datasets = train_test_split(iris.data, iris.target, random_state=50,  test_size=0.3)

train_data, test_data, train_labels, test_labels = datasets

In [4]:
test_labels 

array([1, 1, 0, 0, 2, 2, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 1, 0, 1, 1, 2, 1,
       0, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 0, 0, 1, 2, 1, 0, 0, 1, 2, 0,
       2])

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# we fit the train data
scaler.fit(train_data)

# scaling the train data
train_data = scaler.transform(train_data)
test_data = scaler.transform(test_data)

print(train_data[:3])

[[-0.89476917  0.9626718  -1.3247455  -1.16669293]
 [-1.76468365  0.2671635  -1.38198759 -1.29898533]
 [-0.1491282   1.6581801  -1.15301923 -1.16669293]]


In [6]:
# Training the Model
from sklearn.neural_network import MLPClassifier
# creating an classifier from the model:
mlp = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)

# let's fit the training data to our model
mlp.fit(train_data, train_labels)

MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)

In [7]:
from sklearn.metrics import accuracy_score

predictions_train = mlp.predict(train_data)
print(accuracy_score(predictions_train, train_labels))
predictions_test = mlp.predict(test_data)
print(accuracy_score(predictions_test, test_labels))

0.9904761904761905
0.9333333333333333


In [8]:
from sklearn.metrics import confusion_matrix

confusion_matrix(predictions_train, train_labels)

array([[36,  0,  0],
       [ 0, 32,  0],
       [ 0,  1, 36]])

In [9]:
confusion_matrix(predictions_test, test_labels)

array([[13,  0,  0],
       [ 1, 15,  0],
       [ 0,  2, 14]])